input_dir: "data/CRAC"
output_dir: "out"
samples:
        - CDE0103_S1_L001_R1_001_Control
        - CDE0103_S1_L001_R1_001_SuperPol
        - CDE0103_S1_L001_R1_001_WT
        - CRAC123-DEZ_Control
        - CRAC123-DEZ_SuperPol
        - CRAC123-DEZ_WT
        - CRAC456-DEZ_Controlbmh
        - CRAC456-DEZ_SuperPolbmh
        - CRAC456-DEZ_WTBmh
fastq:  ".fastq"
samtools:
  rm_duplicates: true
  quality: 25
  custom: -F 2052
demultiplexing:
  demultiplex: false
  five_prime: true
  barcode:
    WT: ATTAGC
    SuperPol: GCGCAGC
    Control: TAAGC
  errorate: 0
  extra: ""
umi_tools:
  extract:
    extract-method: "string"
    bc-pattern: NNN
    five_prime: true
    extra: ""
cutadapt:
  extra: ''
  adapters: '-a TGGAATTCTCGG'
threads: 8
genome:
  full_genome:
    dir: 'data/genome'
    name: 'Saccharomyces_cerevisiae.EF2.59.1.0'
    ext: '.fa'
    gtf: 'data/genome/Saccharomyces_cerevisiae.EF2.59.1.3.gtf'
    bed: "data/genome/genes_of_interest.bed"
  rDNA:
    dir: 'data/rDNA'
    name: 'NTS1-2_RDN37-1_NTS2-1_5S'
    ext: '.fa'
    gtf: ""
    bed: "data/rDNA/NTS1-2_RDN37-1_NTS2-1_5S.bed"
fastqc:
  multi_qc_path: "config/multiqc.yaml"
