input_dir: "data"
output_dir: "out"
samples:
  - CDE21_S5
  - CDE20_S4
  - CDE18_S2
  - CDE17_S1
  - CDE19_S3
fastq:  "_L001_R1_001.fastq.gz"
samtools:
  rm_duplicates: true
  quality: 25
  custom: -F 2052
demultiplexing:
  demultiplex: false
  five_prime: true
  barcode:
    WT: ATTAGC
    SuperPol: GCGCAGC
    Control: TAAGC
  errorate: 0
  extra: ""
umi_tools:
  extract:
    extract-method: "string"
    bc-pattern: NNNNN
    five_prime: true
    extra: ""
  trimm:
    trimm: true
    trim_supp: 3
cutadapt:
  extra: ''
  adapters: '-a TGGAATTCTCGG'
threads: 6
genome:
  genome:
    dir: '/home/admin/genome'
    name: 'Saccharomyces_cerevisiae.EF2.59.1.0'
    ext: '.fa'
    gtf: '/home/admin/genome/Saccharomyces_cerevisiae.EF2.59.1.3.gtf'
    bed: "/home/admin/genome/genes_of_interest.bed"
  rDNA:
    dir: '/home/admin/genome'
    name: 'NTS1-2_RDN37-1_NTS2-1_5S'
    ext: '.fa'
    gtf: ""
    bed: "/home/admin/genome/NTS1-2_RDN37-1_NTS2-1_5S.bed"
fastqc:
  multi_qc_path: "config/multiqc.yaml"





 
 
 
 
 
 

