input_dir: "data"
output_dir: "out"
samples:
  - CDE0103_S1_L001_R1_001
fastq:  ".fastq"
samtools:
  rm_duplicates: true
  quality: 25
  custom: -F 2048
demultiplexing:
  barcode:
    WT: NNNATTAGC 
    SuperPol: NNNGCGCAGC
    Control: NNNTAAGC
cutadapt:
  extra: ''
  adapters: '-a TGGAATTCTCGG'
threads: 8
genome:
  dir: 'data/genome'
  name: 'Saccharomyces_cerevisiae.EF2.59.1.0'
  ext: '.fa'
  gtf: 'data/genome/Saccharomyces_cerevisiae.EF2.59.1.3.gtf'
fastqc:
  multi_qc_path: "config/multiqc.yaml"