input_dir: "data"
output_dir: "out"
samples:
  - CDE0103_S1_L001_R1_001
fastq:  ".fastq"
samtools:
  rm_duplicates: true
  quality: 25
  custom: -F 2048
demultiplexing:
  demultiplex: true
  five_prime: true
  barcode:
    WT: ATTAGC
    SuperPol: GCGCAGC
    Control: TAAGC
  errorate: 0
  extra: ""
umi_tools:
  extract:
    extract-method: "string"
    bc-pattern: NNN
    five_prime: true
    extra: ""
cutadapt:
  extra: ''
  adapters: '-a TGGAATTCTCGG'
threads: 8
genome:
  full_genome:
    dir: 'data/genome'
    name: 'Saccharomyces_cerevisiae.EF2.59.1.0'
    ext: '.fa'
    gtf: 'data/genome/Saccharomyces_cerevisiae.EF2.59.1.3.gtf'
  rDNA:
    dir: 'data/rDNA'
    name: '5S_NTS2-1_RDN37-1_NTS1-2'
    ext: '.fa'
    gtf: ""
fastqc:
  multi_qc_path: "config/multiqc.yaml"